rm(list=ls())
library(rio)
library(openxlsx)
files = list.files("C:/Users/sheng/Desktop/excel",pattern="*.xlsx")
myfiles = do.call(rbind, lapply(paste("C:/Users/sheng/Desktop/excel/",files,sep=""),function(x) read.xlsx(x,detectDates = TRUE)))
export(myfiles,'C:/Users/sheng/Desktop/excel/合并文件.xlsx')
